# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b743f6f1742d8d676236c001fc7e4b59341d85a04c84efadc6ca6393c3a3da5e0de64c186af39beaa05cf7dbef963896274d635354ac4ab2b9a3ed7f57d352d9

test:
  secret_key_base: a4433023a5032ada7d0da5396fd8dbf626a698838f6169a611cdc0a62f1267145a76599fb1245ceb716df0fda5faf55aef5069d1fdde8965f38c4fc0adbac040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
